# Generated by Django 4.2.1 on 2023-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_reviews_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('owner', 'project'), name='unique_review'),
        ),
    ]
