# Generated by Django 4.2.1 on 2023-05-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_reviews_unique_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['created_at']},
        ),
    ]
