# Generated by Django 4.2.1 on 2023-05-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_projects_options_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
